
name: india_air_quality_json

on:
  # Triggers the workflow on push or pull request events but only for the main branch
   workflow_dispatch:
#on:
  # schedule:
    #  - cron: '45 * * * *'  

jobs:
  
  build:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          home_dir=$(pwd)
          echo $home_dir
          echo -----------------------------------------------------------------------
          pip install --upgrade pip    
          echo -----------------------------------------------------------------------
          pip install "snowflake-snowpark-python[pandas]"
          echo -----------------------------------------------------------------------
          ls -la
          pwd
          echo ----------------------------------------------------------------------- 
          python $home_dir/ingest_api_data.py
